[project]
name = "pt_agents"
version = "0.1.0"
description = "pt-agents using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<=3.13"
dependencies = [
    "crewai[tools]>=0.86.0,<1.0.0"
]

[project.scripts]
pt_agents = "pt_agents.main:run"
run_crew = "pt_agents.main:run"
train = "pt_agents.main:train"
replay = "pt_agents.main:replay"
test = "pt_agents.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
