reporting_task:
  description: >
    Review the context you got and make it good enough for a report.
  expected_output: >
    Formatted as markdown without '```'
  agent: reporting_analyst
#
port_scanning_task:
  description: >
    Scan the host "scanme.nmap.org" using RustScan
  expected_output: >
    The relevent details from the results of the RustScan or an error message.
  agent: network_penetration_tester
